/**
 * Resolves photo paths from the config ("gallery/01.jpg") to the responsive
 * WebP versions generated by vite-imagetools.
 */
const modules = import.meta.glob<ResponsiveImage>("../assets/images/**/*.{jpg,jpeg,png,webp,avif}", {
  eager: true,
  query: "?responsive",
  import: "default",
});

const byPath = new Map(
  Object.entries(modules).map(([path, image]) => [path.replace("../assets/images/", ""), image]),
);

export function getImage(file?: string): ResponsiveImage | undefined {
  if (!file) return undefined;
  const image = byPath.get(file.replace(/^\/+/, ""));
  if (!image && import.meta.env.DEV) {
    console.warn(`[invitation] Image "${file}" was not found in src/assets/images/`);
  }
  return image;
}
